---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits
Our project will be done using a sequence of save and commits.

## First Verse 
<Put the first two verses of Jabberwocky by Lewis Carrol in this section>
"Beware the Jabberwock, my son!    
The jaws that bite, the claws that catch!  
Beware the Jubjub bird, and shun  
The frumious Bandersnatch!"  
He took his vorpal sword in hand:  
Long time the manxome foe he sought --  
So rested he by the Tumtum tree,  
And stood awhile in thought.



## Second Verse
Two roads diverged in a yellow wood,    
And sorry I could not travel both  
And be one traveler, long I stood  
And looked down one as far as I could  

To where it bent in the undergrowth;  
Then took the other, as just as fair,  
And having perhaps the better claim,  
Because it was grassy and wanted wear;  
Though as for that the passing there  
Had worn them really about the same 

## Third Verse
<Put the first two verses of The Walrus and the Carpenter here>
(from Through the Looking-Glass and What Alice Found There, 1872) 

The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright--  
And this was odd, because it was  
The middle of the night.  

The moon was shining sulkily,  
Because she thought the sun  
Had got no business to be there  
After the day was done--  
"It's very rude of him," she said,  
"To come and spoil the fun!" 

## Last Verse
<Put a short poem of your choice 8-20 lines,here>
You may write me down in history  
With your bitter, twisted lies,  
You may trod me in the very dirt  
But still, like dust, I'll rise.

Does my sassiness upset you?  
Why are you beset with gloom?  
'Cause I walk like I've got oil wells  
Pumping in my living room.

Just like moons and like suns,  
With the certainty of tides,  
Just like hopes springing high,  
Still I'll rise.

Did you want to see me broken?  
Bowed head and lowered eyes?  
Shoulders falling down like teardrops.  
Weakened by my soulful cries.

Does my haughtiness offend you?  
Don't you take it awful hard  
'Cause I laugh like I've got gold mines  
Diggin' in my own back yard.